### ISSUE TITLE
Nest Thermostats not working after upgrading to Homebridge Beta (1.3.0)

### ISSUE THREAD

**Issue by brandonnyc99** [chrisjshull/homebridge-nest#324]
(Cameras are working fine though.)

[10/21/2020, 8:06:37 AM] [Nest] TypeError: this.enqueueConfigurationUpdate is not a function
    at PlatformAccessory.Accessory.addService (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:412:12)
    at new NestThermostatAccessory (/usr/lib/node_modules/homebridge-nest/lib/nest-thermostat-accessory.js:19:40)
    at NestPlatform.<anonymous> (/usr/lib/node_modules/homebridge-nest/index.js:60:47)
    at NestPlatform.<anonymous> (/usr/lib/node_modules/homebridge-nest/index.js:67:17)
    at HomebridgeAPI.<anonymous> (/usr/lib/node_modules/homebridge-nest/index.js:99:40)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[10/21/2020, 8:06:37 AM] [Nest] NOTE: Because we couldn't connect to the Nest service, your Nest devices in HomeKit will not be responsive.

**Comment by adriancable** [comment]
@brandonnyc99 - thanks for this - we'll look into it and, I could be wrong, but feels like a Homebridge/HAP-NodeJS beta issue.

**Comment by dVIAN13** [comment]
I have the same issue with my protect devices.
plugin(v4.4.12)
home bridge(1.3.0beta14)
hap-nodejs(0.9.0-beta.43)

**Comment by adriancable** [comment]
I have reproduced this and have a workaround. I'm currently working on some other fixes for the plug-in, so this will go into the next commit. I'll update you here.

**Comment by adriancable** [comment]
Now fixed in 4.4.13.

**Comment by brandonnyc99** [comment]
Hi @adriancable - Thanks for this. When running the update and latest beta, everything works. I am, however, seeing this int he logs repeating over and over. I went in and set the option for Fan Timer Duration to "15" and its still happening.

[10/26/2020, 8:13:45 PM] Received warning for the plugin 'homebridge-nest' from the characteristic 'Fan Timer Duration': characteristic was supplied illegal value: number 1800 exceeded maximum of 1440.

**Comment by adriancable** [comment]
@brandonnyc99 - I think your config.json is wrong, and there is also a bug on our side which we will fix. (although the bug is pretty harmless, and has no impact apart from producing that annoying warning)

Please can you post the fanTimerDuration line from your config.json here. Thanks!

**Comment by brandonnyc99** [comment]
Thank you again @adriancable.

Fan duration was empty in the config when I first installed it so I went and made it 15 to see if the error would stop. Neither 15 or empty made a difference.

            },
            "fanDurationMinutes": 15,
            "options": [
                "x"

**Comment by adriancable** [comment]
@brandonnyc99 - 4.4.14 is now published which should fix this warning.
