### ISSUE TITLE
Homebridge Nest often shows wrong temperature indoors in HomeKit

### ISSUE THREAD

**Issue by AlexPygin** [chrisjshull/homebridge-nest#448]
**Describe the bug**

https://youtube.com/shorts/-Kd4PRMol5c?feature=share

**To Reproduce**
1. This has been happening constantly for a long time. I just usually open the nest app, but I’d like to move away from that. Not sure when/if it should be accurate in home, or if this plugin is just for setting temperature. Usually happens if I don’t reboot Homebridge for a while

**Expected behavior**
The thermostat in HomeKit shows the correct temperature

Include with your bug report this version info:
```sh
node --version
homebridge --version
```
V14.17.0
1.3.5

Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest`

Also include debug log output from startup through seeing the issue:
`DEBUG=* homebridge -D`
restarting Homebridge  makes it show correct temp

**Comment by AlexPygin** [comment]
The nest app shows the current temperature indoors is 69°. When I open control center, it shows 72° inside. I open Homebridge logs to show you that the Nest was controlled recently, and controlled correctly, so the set temperature of 81 is correct. I then open the home app where it shows 72° inside, same as control center.

The correct temperature inside is 69° but Homebridge is showing 72°. As time goes on, this can get wildly inaccurate. On hot days where it can get up to 80° inside, the Nest app will show that correctly, but Homebridge would show some other older cached temperature like 73 or something.

**Comment by adriancable** [comment]
Can you please record a longer log (like in your video, but running for several hours) including the time period where the reported temperature is wrong. Then email me the log at adrian.cable@gmail.com, and tell me at the point in time you stopped recording what the temperature as registered in the Home app is, and also what the temperature as registered in the Nest app is. Thanks!

Since no-one else has reported anything like this, I am suspecting some network issue (possibly mDNS related) whereby your iPhone is losing connection to the Homebridge machine, so it doesn't receive updates.

**Comment by AlexPygin** [comment]
For example right now the temperature is 72° indoors but Homebridge says it’s 68° in here

It hasn’t been 68° indoors since probably 9am today, and was 75° inside a few hours ago, so it’s been wrong since this morning. I can perform whatever troubleshooting steps you want because this always happens

**Comment by adriancable** [comment]
@AlexPygin - we don't need additional videos. Please just record a long Homebridge log (e.g. one complete day) as we requested, covering the period where the temperature goes wrong, and then email me the 'correct' and 'incorrect' temperatures as of the end of the log.

**Comment by AlexPygin** [comment]
https://youtu.be/5ZqEeuHyBaM

You can clearly see that Homebridge is updating the set temperature for the nest, but it doesn’t show the correct indoor temperature. I’ll record one more video showing that a reboot fixes it

**Comment by AlexPygin** [comment]
Sure, will do that

**Comment by AlexPygin** [comment]
Do you want any debug flags set?

**Comment by AlexPygin** [comment]
Is hasn’t manifested yet, but I feel like it does after I restart my router, so I’ll try that today and see if it happens

**Comment by adriancable** [comment]
Fixed in 4.6.3.

**Comment by gtg465x** [comment]
Update: This bug is happening to me again (still on 4.6.2). Took a couple weeks after a reboot before it started happening. I have verbose logging turned on, but there are no errors when it happens. Changing temperate from the Apple Home app works, but after a few seconds, the Home app goes back to displaying the incorrect temperature even though the temperature is set properly on the thermostat itself. I did download my log file and found a couple types of Nest errors that seem to happen every couple days, but not sure if they're related to the issue.

```
[03/11/2021, 09:02:13] [Nest] API observe: error Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read'
}
[03/11/2021, 09:02:13] [Nest] Retrying in 10 seconds.
```

```
[03/11/2021, 13:33:54] [Nest] API observe: error Error [ERR_HTTP2_STREAM_ERROR]: Stream closed with error code NGHTTP2_INTERNAL_ERROR
    at ClientHttp2Stream._destroy (internal/http2/core.js:2193:13)
    at ClientHttp2Stream.destroy (internal/streams/destroy.js:39:8)
    at Http2Stream.onStreamClose (internal/http2/core.js:512:12) {
  code: 'ERR_HTTP2_STREAM_ERROR'
}
[03/11/2021, 13:33:54] [Nest] Retrying in 10 seconds.
```

I'm updating to 4.6.3 now. Fingers crossed.

**Comment by adriancable** [comment]
@gtg465x - those warnings are not related to your issue, and are completely normal. They are a duplicate of the pinned issue #424.

**Comment by blabus** [comment]
I'm still experiencing this exact issue. Should I open a new issue?

**Comment by adriancable** [comment]
@blabus - can you please email me at adrian.cable@gmail.com and I'll get back to you with the info I need to debug. Thanks.
